// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJdrxsa1XLPLWNlZHssp6KkEXdyDDs4xg',
    appId: '1:691816391292:web:30f09b492f8453de249ff9',
    messagingSenderId: '691816391292',
    projectId: 'employee-attendance-2bc9f',
    authDomain: 'employee-attendance-2bc9f.firebaseapp.com',
    storageBucket: 'employee-attendance-2bc9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmLuVt4lq1_s7uZsZU4clqFbM2TZQV2ZA',
    appId: '1:691816391292:android:1d38d141af2a5a54249ff9',
    messagingSenderId: '691816391292',
    projectId: 'employee-attendance-2bc9f',
    storageBucket: 'employee-attendance-2bc9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhR9iMlbsT1FtS1MpYh4jzcllRnIel_Ao',
    appId: '1:691816391292:ios:85d706ecba372db8249ff9',
    messagingSenderId: '691816391292',
    projectId: 'employee-attendance-2bc9f',
    storageBucket: 'employee-attendance-2bc9f.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhR9iMlbsT1FtS1MpYh4jzcllRnIel_Ao',
    appId: '1:691816391292:ios:85d706ecba372db8249ff9',
    messagingSenderId: '691816391292',
    projectId: 'employee-attendance-2bc9f',
    storageBucket: 'employee-attendance-2bc9f.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJdrxsa1XLPLWNlZHssp6KkEXdyDDs4xg',
    appId: '1:691816391292:web:d9bc9466db094c0e249ff9',
    messagingSenderId: '691816391292',
    projectId: 'employee-attendance-2bc9f',
    authDomain: 'employee-attendance-2bc9f.firebaseapp.com',
    storageBucket: 'employee-attendance-2bc9f.firebasestorage.app',
  );
}
